// imagens.js
var linksImagens = {
  "Poets Can't Be Murdered - Trevor": "https://i.imgur.com/yhwmxiR.png",
  "Overgrown - Eric": "https://i.imgur.com/SjmmVKv.png",
  "The Drive - Ava": "https://i.imgur.com/xkyQrbf.png",
  "MELANCHOLIA - Alana Grace": "https://i.imgur.com/n5OTHPi.png",
  "Salute - 4Music": "https://i.imgur.com/4lwZZtP.png",
  "Before Sunrise (Original Motion Picture Soundtrack) - Conan Woolridge, Fiona": "https://i.imgur.com/dCHj2tL.png",
  "Dreamscape - Aria": "https://i.imgur.com/YOeKr4e.png",
  "Forbidden Whispers - Conan Woolridge": "https://i.imgur.com/dcXh0vd.png",
  "What Ever Happened? - Even Grace": "https://i.imgur.com/4UxqnEn.png",
  "everlasting - Liz": "https://i.imgur.com/UP6Su3j.png",
  "i owe it to myself - Owen Graham": "https://i.imgur.com/QeOU7TT.png",
  "side-eyed means - Logan": "https://i.imgur.com/7kv3rmq.png",
  "KIDS SEE GHOSTS - Trevor": "https://i.imgur.com/HaozlBp.png",
  "House Of The Rising Sun - Ava": "https://i.imgur.com/sifpteD.png",
  "A Brief Inquiry Into Online Relationships - Even Grace": "https://i.imgur.com/ZyaFSC1.png",
  "Purple Dream - Even Grace": "https://i.imgur.com/gssMuy8.png",
  "Gone Now - Even Grace": "https://i.imgur.com/40ePcbw.png",
  "Confessions Of A Broken Heart (Deluxe) - Fiona": "https://i.imgur.com/BbAnTz7.jpg",
  "meaningless - Anthony": "https://i.imgur.com/YPbjHzk.png",
  "I Really Don't Wanna Hear It Anymore - Holligan": "https://pbs.twimg.com/media/FycJA3HacAAl4w7.jpg:large",
};
