var linksImagens = {
  "Bloodsucker - Ava": "https://i.imgur.com/n3DwAZF.png",
  "Rumors - Owen Graham": "https://i.imgur.com/dhc5YTC.jpg",
  "Salute - 4Music": "https://i.imgur.com/oxCDtRj.jpeg",
  "Dilemma - Aria, Zara": "https://i.imgur.com/yQnenND.png",
  "Memories From Home - Conan Woolridge": "https://i.imgur.com/65gXFm7.png",
  "Eyes On Me - Aria": "https://i.imgur.com/DZh9I3s.png",
  "The Suburbs - Even Grace": "https://i.imgur.com/8QfuQKE.png",
  "Stronger Than Love - Aria, Trevor": "https://i.imgur.com/YOeKr4e.png",
  "Father Sins - Trevor": "https://i.imgur.com/5kfkjb9.pngimagens-singles.js",
  "20 - Conan Woolridge": "https://i.imgur.com/fGm30Zb.png",
  "Family Ties - Miles Carson, Trevor": "https://i.imgur.com/hRC7dD8.jpeg",
  "Sweetheart - Holligan": "https://i.imgur.com/gTCOEAJ.png",
  "Boom Boom - Aria, Liza, Hannah": "https://i.imgur.com/8yrpSbT.png",
  "Wings - 4Music": "https://i.imgur.com/FFwDAJ2.png",
  "Inner Self - Trevor": "https://i.imgur.com/HaozlBp.png",
};
